### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by vamshi9** [lukaswhite/face-detection-nodejs#4]
node-pre-gyp install --fallback-to-build

**Comment by lukaswhite** [comment]
Not enough information

**Comment by vamshi9** [comment]
when I run vagrant ssh it is throwing errors!

**Comment by lukaswhite** [comment]
In the original issue it talks about the `node-pre-gyp` command, then in your comment you say the problem is with `vagrant ssh`?

"Some errors" tells me nothing about the problem.
